name: CI

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.6 # Change this to your desired Python version

    - name: Install dependencies
      run: |
        make requirements

    - name: Apply format 
      run: |
        make format

    - name: Run tests
      run: |
        make test

  deploy:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/{{ secrets.ECR_REPO_NAME }}:latest .
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/{{ secrets.ECR_REPO_NAME }}:latest

      # - name: Deploy to AWS Elastic Beanstalk
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}
      #   run: |
      #     aws elasticbeanstalk create-application-version 
      #     --application-name {{ secrets.BEANSTALK_APP_NAME }} 
      #     --version-label v${GITHUB_RUN_NUMBER} 
      #     --source-bundle S3Bucket=${{ secrets.AWS_S3_BUCKET }},S3Key=${{ secrets.AWS_S3_KEY }}/{{ secrets.ECR_REPO_NAME }}-${{ github.sha }}.zip
      #     aws elasticbeanstalk update-environment 
      #     --environment-name {{ secrets.BEANSTALK_ENV_NAME }} 
      #     --version-label v${GITHUB_RUN_NUMBER}
